import Link from 'next/link'

export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-zinc-950 text-zinc-100">
      <div className="max-w-3xl mx-auto px-6 py-16">
        <Link href="/" className="text-sm text-zinc-400 hover:text-white">← Back to ThreadForge</Link>
        
        <h1 className="text-4xl font-semibold tracking-tighter mt-8 mb-8">Terms of Service</h1>
        
        <p className="text-sm text-zinc-500 mb-8">Last updated: {new Date().toLocaleDateString()}</p>

        <div className="prose prose-invert max-w-none text-zinc-300 space-y-6 text-[15px] leading-relaxed">

          <h2 className="text-xl font-semibold text-white mt-10">1. Acceptance of Terms</h2>
          <p>By accessing or using ThreadForge ("the Service"), you agree to be bound by these Terms of Service. If you do not agree, you may not use the Service.</p>

          <h2 className="text-xl font-semibold text-white mt-10">2. Description of Service</h2>
          <p>ThreadForge is an AI-powered tool that generates X (Twitter) threads based on topics you provide. We offer a free tier with limited generations and a paid one-time purchase for unlimited access.</p>

          <h2 className="text-xl font-semibold text-white mt-10">3. Payments and Refunds</h2>
          <ul className="list-disc pl-6 space-y-2">
            <li>Unlimited access requires a one-time payment of $9.</li>
            <li><strong>All sales are final.</strong> Because this is a digital product delivered immediately, we do not offer refunds after purchase.</li>
            <li>You are responsible for any applicable taxes.</li>
          </ul>

          <h2 className="text-xl font-semibold text-white mt-10">4. User Accounts</h2>
          <p>You must create an account (via Google or email) to use the full features of the Service. You are responsible for maintaining the security of your account.</p>

          <h2 className="text-xl font-semibold text-white mt-10">5. AI-Generated Content</h2>
          <p>Threads generated by ThreadForge are created using artificial intelligence. We do not guarantee the accuracy, quality, originality, or suitability of any generated content. You are solely responsible for reviewing and deciding how to use any content generated by the Service.</p>

          <h2 className="text-xl font-semibold text-white mt-10">6. License</h2>
          <p>Upon successful payment, you are granted a personal, non-exclusive, non-transferable license to use the generated threads. You may not resell or redistribute access to the ThreadForge service itself.</p>

          <h2 className="text-xl font-semibold text-white mt-10">7. Prohibited Uses</h2>
          <p>You agree not to:</p>
          <ul className="list-disc pl-6 space-y-2">
            <li>Use the Service to generate spam, illegal, hateful, or harmful content</li>
            <li>Abuse the free tier (including creating multiple accounts to bypass limits)</li>
            <li>Reverse engineer, copy, or attempt to extract the underlying models or technology</li>
            <li>Use the Service in a way that violates X's (Twitter's) rules or any applicable laws</li>
          </ul>

          <h2 className="text-xl font-semibold text-white mt-10">8. Termination</h2>
          <p>We reserve the right to suspend or terminate your access to the Service at any time if you violate these Terms.</p>

          <h2 className="text-xl font-semibold text-white mt-10">9. Disclaimer of Warranties</h2>
          <p>The Service is provided "as is" without warranties of any kind, whether express or implied.</p>

          <h2 className="text-xl font-semibold text-white mt-10">10. Limitation of Liability</h2>
          <p>To the maximum extent permitted by law, ThreadForge shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the Service.</p>

          <h2 className="text-xl font-semibold text-white mt-10">11. Governing Law</h2>
          <p>These Terms shall be governed by and construed in accordance with the laws of the United States and the laws of the State of [Your State], without regard to its conflict of law principles.</p>

          <h2 className="text-xl font-semibold text-white mt-10">12. Changes to Terms</h2>
          <p>We may update these Terms from time to time. Continued use of the Service after changes are posted constitutes acceptance of the updated Terms.</p>

          <h2 className="text-xl font-semibold text-white mt-10">13. Contact</h2>
          <p>If you have any questions about these Terms of Service, please contact us at:</p>
          <p><a href="mailto:legal@threadforge.com" className="text-white underline">legal@threadforge.com</a></p>

        </div>
      </div>
    </div>
  )
}
